In [64]:
import torch
import torch.nn as nn

#Create Neural Network

In [65]:
model = nn.Sequential(
    nn.Linear(1, 1),
    nn.Tanh(),
    nn.Linear(1, 1)
)

In [66]:
model

Sequential(
  (0): Linear(in_features=1, out_features=1, bias=True)
  (1): Tanh()
  (2): Linear(in_features=1, out_features=1, bias=True)
)

# Set Weights

In [67]:
with torch.no_grad():

  model[0].weight.fill_(2.0)
  model[0].bias.fill_(1.0)

  model[2].weight.fill_(3.0)
  model[2].bias.fill_(5.0)

Create Input t=0.5

In [68]:
t = torch.tensor([[0.5]], requires_grad=True)

In [69]:
t

tensor([[0.5000]], requires_grad=True)

# Forward Pass

In [70]:
T=model(t)

In [71]:
print(T)

tensor([[7.8921]], grad_fn=<AddmmBackward0>)


# derivative dT/dt

In [72]:
dT_dt=torch.autograd.grad(
    outputs=T,
    inputs=t,
    grad_outputs=torch.ones_like(T),
    create_graph=True
)[0]

In [73]:
print("dT_dt",dT_dt)

dT_dt tensor([[0.4239]], grad_fn=<TBackward0>)


#Residual

In [74]:
residual=dT_dt+0.1*(T-25)
print("REsidual",residual)

REsidual tensor([[-1.2869]], grad_fn=<AddBackward0>)


#Physics Loss

In [75]:
physics_loss=torch.mean(residual**2)
physics_loss

tensor(1.6561, grad_fn=<MeanBackward0>)

# Initial Condition

In [78]:
t0=torch.tensor([[0.0]],requires_grad=True)
T0=model(t0)
print(T0)

tensor([[7.2848]], grad_fn=<AddmmBackward0>)


#Initial Condition LOss

In [80]:
ic_loss=torch.mean((T0-100)**2)
ic_loss

tensor(8596.1113, grad_fn=<MeanBackward0>)

#Total_loss

In [81]:
total_loss=physics_loss+ic_loss
print(total_loss)

tensor(8597.7676, grad_fn=<AddBackward0>)


#Backpropagation

In [82]:
total_loss.backward()

In [93]:
print(model[0].weight.grad)
print(model[0].bias.grad)

print(model[2].weight.grad)
print(model[2].bias.grad)

tensor([[0.4790]])
tensor([-231.5790])
tensor([[-141.8345]])
tensor([-185.6878])
