In [1]:
import torch

In [2]:
x = torch.tensor(
    [[0.5]],
    dtype=torch.float32,
    requires_grad=True
)
x.shape

torch.Size([1, 1])

In [3]:
t = torch.tensor(
    [[0.2]],
    dtype=torch.float32,
    requires_grad=True
)
t

tensor([[0.2000]], requires_grad=True)

# Simple Neural Network

In [4]:
z=2*x+3*t+1
h=torch.tanh(z)
T=4*h+5

print("Z: ",z)
print("h: ",h)
print("T: ",T)

Z:  tensor([[2.6000]], grad_fn=<AddBackward0>)
h:  tensor([[0.9890]], grad_fn=<TanhBackward0>)
T:  tensor([[8.9561]], grad_fn=<AddBackward0>)


# dT/dt

In [8]:
T_t=torch.autograd.grad(
    outputs=T,
    inputs=t,
    grad_outputs=torch.ones_like(T),
    create_graph=True)[0]
T_t

tensor([[0.2619]], grad_fn=<MulBackward0>)

# dT/dx

In [9]:
T_x=torch.autograd.grad(
    outputs=T,
    inputs=x,
    grad_outputs=torch.ones_like(T),
    create_graph=True
)[0]
T_x

tensor([[0.1746]], grad_fn=<MulBackward0>)

#d^2T/dx^2

In [10]:
T_xx=torch.autograd.grad(
  outputs=T_x,
  inputs=x,
  grad_outputs=torch.ones_like(T_x),
  create_graph=True
)[0]
T_xx

tensor([[-0.6907]], grad_fn=<MulBackward0>)

#Physics Residual

In [11]:
alpha=0.01

residual=T_t-alpha*T_xx
print("residual : ",residual)

residual :  tensor([[0.2688]], grad_fn=<SubBackward0>)


In [13]:
physics_loss=torch.mean(residual**2)
physics_loss

tensor(0.0723, grad_fn=<MeanBackward0>)